var database = [
    {
      "Number": 1,
      "Name": "Bulbasaur",
      "Type 1": "Grass",
      "Type 2": "Poison",
      "HP": 45,
      "Attack": 49,
      "Defense": 49,
      "Sp. Atk": 65,
      "Sp. Def": 65,
      "Speed": 45,
      "Total": 318
    },
    {
      "Number": 2,
      "Name": "Ivysaur",
      "Type 1": "Grass",
      "Type 2": "Poison",
      "HP": 60,
      "Attack": 62,
      "Defense": 63,
      "Sp. Atk": 80,
      "Sp. Def": 80,
      "Speed": 60,
      "Total": 405
    },
    {
      "Number": 3,
      "Name": "Venusaur",
      "Type 1": "Grass",
      "Type 2": "Poison",
      "HP": 80,
      "Attack": 82,
      "Defense": 83,
      "Sp. Atk": 100,
      "Sp. Def": 100,
      "Speed": 80,
      "Total": 525
    },
    {
      "Number": 4,
      "Name": "Charmander",
      "Type 1": "Fire",
      "Type 2": "",
      "HP": 39,
      "Attack": 52,
      "Defense": 43,
      "Sp. Atk": 60,
      "Sp. Def": 50,
      "Speed": 65,
      "Total": 309
    },
    {
      "Number": 5,
      "Name": "Charmeleon",
      "Type 1": "Fire",
      "Type 2": "",
      "HP": 58,
      "Attack": 64,
      "Defense": 58,
      "Sp. Atk": 80,
      "Sp. Def": 65,
      "Speed": 80,
      "Total": 405
    },
    {
      "Number": 6,
      "Name": "Charizard",
      "Type 1": "Fire",
      "Type 2": "Flying",
      "HP": 78,
      "Attack": 84,
      "Defense": 78,
      "Sp. Atk": 109,
      "Sp. Def": 85,
      "Speed": 100,
      "Total": 534
    },
    {
      "Number": 7,
      "Name": "Squirtle",
      "Type 1": "Water",
      "Type 2": "",
      "HP": 44,
      "Attack": 48,
      "Defense": 65,
      "Sp. Atk": 50,
      "Sp. Def": 64,
      "Speed": 43,
      "Total": 314
    },
    {
      "Number": 8,
      "Name": "Wartortle",
      "Type 1": "Water",
      "Type 2": "",
      "HP": 59,
      "Attack": 63,
      "Defense": 80,
      "Sp. Atk": 65,
      "Sp. Def": 80,
      "Speed": 58,
      "Total": 405
    },
    {
      "Number": 9,
      "Name": "Blastoise",
      "Type 1": "Water",
      "Type 2": "",
      "HP": 79,
      "Attack": 83,
      "Defense": 100,
      "Sp. Atk": 85,
      "Sp. Def": 105,
      "Speed": 78,
      "Total": 530
    },
    {
      "Number": 10,
      "Name": "Caterpie",
      "Type 1": "Bug",
      "Type 2": "",
      "HP": 45,
      "Attack": 30,
      "Defense": 35,
      "Sp. Atk": 20,
      "Sp. Def": 20,
      "Speed": 45,
      "Total": 195
    },
    {
      "Number": 11,
      "Name": "Metapod",
      "Type 1": "Bug",
      "Type 2": "",
      "HP": 50,
      "Attack": 20,
      "Defense": 55,
      "Sp. Atk": 25,
      "Sp. Def": 25,
      "Speed": 30,
      "Total": 205
    },
    {
      "Number": 12,
      "Name": "Butterfree",
      "Type 1": "Bug",
      "Type 2": "Flying",
      "HP": 60,
      "Attack": 45,
      "Defense": 50,
      "Sp. Atk": 80,
      "Sp. Def": 80,
      "Speed": 70,
      "Total": 385
    },
    {
      "Number": 13,
      "Name": "Weedle",
      "Type 1": "Bug",
      "Type 2": "Poison",
      "HP": 40,
      "Attack": 35,
      "Defense": 30,
      "Sp. Atk": 20,
      "Sp. Def": 20,
      "Speed": 50,
      "Total": 195
    },
    {
      "Number": 14,
      "Name": "Kakuna",
      "Type 1": "Bug",
      "Type 2": "Poison",
      "HP": 45,
      "Attack": 25,
      "Defense": 50,
      "Sp. Atk": 25,
      "Sp. Def": 25,
      "Speed": 35,
      "Total": 205
    },
    {
      "Number": 15,
      "Name": "Beedrill",
      "Type 1": "Bug",
      "Type 2": "Poison",
      "HP": 65,
      "Attack": 80,
      "Defense": 40,
      "Sp. Atk": 45,
      "Sp. Def": 80,
      "Speed": 75,
      "Total": 385
    },
    {
      "Number": 16,
      "Name": "Pidgey",
      "Type 1": "Normal",
      "Type 2": "Flying",
      "HP": 40,
      "Attack": 45,
      "Defense": 40,
      "Sp. Atk": 35,
      "Sp. Def": 35,
      "Speed": 56,
      "Total": 251
    },
    {
      "Number": 17,
      "Name": "Pidgeotto",
      "Type 1": "Normal",
      "Type 2": "Flying",
      "HP": 63,
      "Attack": 60,
      "Defense": 55,
      "Sp. Atk": 50,
      "Sp. Def": 50,
      "Speed": 71,
      "Total": 349
    },
    {
      "Number": 18,
      "Name": "Pidgeot",
      "Type 1": "Normal",
      "Type 2": "Flying",
      "HP": 83,
      "Attack": 80,
      "Defense": 75,
      "Sp. Atk": 70,
      "Sp. Def": 70,
      "Speed": 91,
      "Total": 469
    },
    {
      "Number": 19,
      "Name": "Rattata",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 30,
      "Attack": 56,
      "Defense": 35,
      "Sp. Atk": 25,
      "Sp. Def": 35,
      "Speed": 72,
      "Total": 253
    },
    {
      "Number": 20,
      "Name": "Raticate",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 55,
      "Attack": 81,
      "Defense": 60,
      "Sp. Atk": 50,
      "Sp. Def": 70,
      "Speed": 97,
      "Total": 413
    },
    {
      "Number": 21,
      "Name": "Spearow",
      "Type 1": "Normal",
      "Type 2": "Flying",
      "HP": 40,
      "Attack": 60,
      "Defense": 30,
      "Sp. Atk": 31,
      "Sp. Def": 31,
      "Speed": 70,
      "Total": 262
    },
    {
      "Number": 22,
      "Name": "Fearow",
      "Type 1": "Normal",
      "Type 2": "Flying",
      "HP": 65,
      "Attack": 90,
      "Defense": 65,
      "Sp. Atk": 61,
      "Sp. Def": 61,
      "Speed": 100,
      "Total": 442
    },
    {
      "Number": 23,
      "Name": "Ekans",
      "Type 1": "Poison",
      "Type 2": "",
      "HP": 35,
      "Attack": 60,
      "Defense": 44,
      "Sp. Atk": 40,
      "Sp. Def": 54,
      "Speed": 55,
      "Total": 288
    },
    {
      "Number": 24,
      "Name": "Arbok",
      "Type 1": "Poison",
      "Type 2": "",
      "HP": 60,
      "Attack": 85,
      "Defense": 69,
      "Sp. Atk": 65,
      "Sp. Def": 79,
      "Speed": 80,
      "Total": 438
    },
    {
      "Number": 25,
      "Name": "Pikachu",
      "Type 1": "Electric",
      "Type 2": "",
      "HP": 35,
      "Attack": 55,
      "Defense": 30,
      "Sp. Atk": 50,
      "Sp. Def": 40,
      "Speed": 90,
      "Total": 300
    },
    {
      "Number": 26,
      "Name": "Raichu",
      "Type 1": "Electric",
      "Type 2": "",
      "HP": 60,
      "Attack": 90,
      "Defense": 55,
      "Sp. Atk": 90,
      "Sp. Def": 80,
      "Speed": 100,
      "Total": 475
    },
    {
      "Number": 27,
      "Name": "Sandshrew",
      "Type 1": "Ground",
      "Type 2": "",
      "HP": 50,
      "Attack": 75,
      "Defense": 85,
      "Sp. Atk": 20,
      "Sp. Def": 30,
      "Speed": 40,
      "Total": 300
    },
    {
      "Number": 28,
      "Name": "Sandslash",
      "Type 1": "Ground",
      "Type 2": "",
      "HP": 75,
      "Attack": 100,
      "Defense": 110,
      "Sp. Atk": 45,
      "Sp. Def": 55,
      "Speed": 65,
      "Total": 450
    },
    {
      "Number": 29,
      "Name": "Nidoran (F)",
      "Type 1": "Poison",
      "Type 2": "",
      "HP": 55,
      "Attack": 47,
      "Defense": 52,
      "Sp. Atk": 40,
      "Sp. Def": 40,
      "Speed": 41,
      "Total": 275
    },
    {
      "Number": 30,
      "Name": "Nidorina",
      "Type 1": "Poison",
      "Type 2": "",
      "HP": 70,
      "Attack": 62,
      "Defense": 67,
      "Sp. Atk": 55,
      "Sp. Def": 55,
      "Speed": 56,
      "Total": 365
    },
    {
      "Number": 31,
      "Name": "Nidoqueen",
      "Type 1": "Poison",
      "Type 2": "Ground",
      "HP": 90,
      "Attack": 82,
      "Defense": 87,
      "Sp. Atk": 75,
      "Sp. Def": 85,
      "Speed": 76,
      "Total": 495
    },
    {
      "Number": 32,
      "Name": "Nidoran (M)",
      "Type 1": "Poison",
      "Type 2": "",
      "HP": 46,
      "Attack": 57,
      "Defense": 40,
      "Sp. Atk": 40,
      "Sp. Def": 40,
      "Speed": 50,
      "Total": 273
    },
    {
      "Number": 33,
      "Name": "Nidorino",
      "Type 1": "Poison",
      "Type 2": "",
      "HP": 61,
      "Attack": 72,
      "Defense": 57,
      "Sp. Atk": 55,
      "Sp. Def": 55,
      "Speed": 65,
      "Total": 365
    },
    {
      "Number": 34,
      "Name": "Nidoking",
      "Type 1": "Poison",
      "Type 2": "Ground",
      "HP": 81,
      "Attack": 92,
      "Defense": 77,
      "Sp. Atk": 85,
      "Sp. Def": 75,
      "Speed": 85,
      "Total": 495
    },
    {
      "Number": 35,
      "Name": "Clefairy",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 70,
      "Attack": 45,
      "Defense": 48,
      "Sp. Atk": 60,
      "Sp. Def": 65,
      "Speed": 35,
      "Total": 323
    },
    {
      "Number": 36,
      "Name": "Clefable",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 95,
      "Attack": 70,
      "Defense": 73,
      "Sp. Atk": 85,
      "Sp. Def": 90,
      "Speed": 60,
      "Total": 473
    },
    {
      "Number": 37,
      "Name": "Vulpix",
      "Type 1": "Fire",
      "Type 2": "",
      "HP": 38,
      "Attack": 41,
      "Defense": 40,
      "Sp. Atk": 50,
      "Sp. Def": 65,
      "Speed": 65,
      "Total": 299
    },
    {
      "Number": 38,
      "Name": "Ninetales",
      "Type 1": "Fire",
      "Type 2": "",
      "HP": 73,
      "Attack": 76,
      "Defense": 75,
      "Sp. Atk": 81,
      "Sp. Def": 100,
      "Speed": 100,
      "Total": 505
    },
    {
      "Number": 39,
      "Name": "Jigglypuff",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 115,
      "Attack": 45,
      "Defense": 20,
      "Sp. Atk": 45,
      "Sp. Def": 25,
      "Speed": 20,
      "Total": 270
    },
    {
      "Number": 40,
      "Name": "Wigglytuff",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 140,
      "Attack": 70,
      "Defense": 45,
      "Sp. Atk": 75,
      "Sp. Def": 50,
      "Speed": 45,
      "Total": 425
    },
    {
      "Number": 41,
      "Name": "Zubat",
      "Type 1": "Poison",
      "Type 2": "Flying",
      "HP": 40,
      "Attack": 45,
      "Defense": 35,
      "Sp. Atk": 30,
      "Sp. Def": 40,
      "Speed": 55,
      "Total": 245
    },
    {
      "Number": 42,
      "Name": "Golbat",
      "Type 1": "Poison",
      "Type 2": "Flying",
      "HP": 75,
      "Attack": 80,
      "Defense": 70,
      "Sp. Atk": 65,
      "Sp. Def": 75,
      "Speed": 90,
      "Total": 455
    },
    {
      "Number": 43,
      "Name": "Oddish",
      "Type 1": "Grass",
      "Type 2": "Poison",
      "HP": 45,
      "Attack": 50,
      "Defense": 55,
      "Sp. Atk": 75,
      "Sp. Def": 65,
      "Speed": 30,
      "Total": 320
    },
    {
      "Number": 44,
      "Name": "Gloom",
      "Type 1": "Grass",
      "Type 2": "Poison",
      "HP": 60,
      "Attack": 65,
      "Defense": 70,
      "Sp. Atk": 85,
      "Sp. Def": 75,
      "Speed": 40,
      "Total": 395
    },
    {
      "Number": 45,
      "Name": "Vileplume",
      "Type 1": "Grass",
      "Type 2": "Poison",
      "HP": 75,
      "Attack": 80,
      "Defense": 85,
      "Sp. Atk": 100,
      "Sp. Def": 90,
      "Speed": 50,
      "Total": 480
    },
    {
      "Number": 46,
      "Name": "Paras",
      "Type 1": "Bug",
      "Type 2": "Grass",
      "HP": 35,
      "Attack": 70,
      "Defense": 55,
      "Sp. Atk": 45,
      "Sp. Def": 55,
      "Speed": 25,
      "Total": 285
    },
    {
      "Number": 47,
      "Name": "Parasect",
      "Type 1": "Bug",
      "Type 2": "Grass",
      "HP": 60,
      "Attack": 95,
      "Defense": 80,
      "Sp. Atk": 60,
      "Sp. Def": 80,
      "Speed": 30,
      "Total": 405
    },
    {
      "Number": 48,
      "Name": "Venonat",
      "Type 1": "Bug",
      "Type 2": "Poison",
      "HP": 60,
      "Attack": 55,
      "Defense": 50,
      "Sp. Atk": 40,
      "Sp. Def": 55,
      "Speed": 45,
      "Total": 305
    },
    {
      "Number": 49,
      "Name": "Venomoth",
      "Type 1": "Bug",
      "Type 2": "Poison",
      "HP": 70,
      "Attack": 65,
      "Defense": 60,
      "Sp. Atk": 90,
      "Sp. Def": 75,
      "Speed": 90,
      "Total": 450
    },
    {
      "Number": 50,
      "Name": "Diglett",
      "Type 1": "Ground",
      "Type 2": "",
      "HP": 10,
      "Attack": 55,
      "Defense": 25,
      "Sp. Atk": 35,
      "Sp. Def": 45,
      "Speed": 95,
      "Total": 265
    },
    {
      "Number": 51,
      "Name": "Dugtrio",
      "Type 1": "Ground",
      "Type 2": "",
      "HP": 35,
      "Attack": 80,
      "Defense": 50,
      "Sp. Atk": 50,
      "Sp. Def": 70,
      "Speed": 120,
      "Total": 405
    },
    {
      "Number": 52,
      "Name": "Meowth",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 40,
      "Attack": 45,
      "Defense": 35,
      "Sp. Atk": 40,
      "Sp. Def": 40,
      "Speed": 90,
      "Total": 290
    },
    {
      "Number": 53,
      "Name": "Persian",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 65,
      "Attack": 70,
      "Defense": 60,
      "Sp. Atk": 65,
      "Sp. Def": 65,
      "Speed": 115,
      "Total": 440
    },
    {
      "Number": 54,
      "Name": "Psyduck",
      "Type 1": "Water",
      "Type 2": "",
      "HP": 50,
      "Attack": 52,
      "Defense": 48,
      "Sp. Atk": 65,
      "Sp. Def": 50,
      "Speed": 55,
      "Total": 320
    },
    {
      "Number": 55,
      "Name": "Golduck",
      "Type 1": "Water",
      "Type 2": "",
      "HP": 80,
      "Attack": 82,
      "Defense": 78,
      "Sp. Atk": 95,
      "Sp. Def": 80,
      "Speed": 85,
      "Total": 500
    },
    {
      "Number": 56,
      "Name": "Mankey",
      "Type 1": "Fighting",
      "Type 2": "",
      "HP": 40,
      "Attack": 80,
      "Defense": 35,
      "Sp. Atk": 35,
      "Sp. Def": 45,
      "Speed": 70,
      "Total": 305
    },
    {
      "Number": 57,
      "Name": "Primeape",
      "Type 1": "Fighting",
      "Type 2": "",
      "HP": 65,
      "Attack": 105,
      "Defense": 60,
      "Sp. Atk": 60,
      "Sp. Def": 70,
      "Speed": 95,
      "Total": 455
    },
    {
      "Number": 58,
      "Name": "Growlithe",
      "Type 1": "Fire",
      "Type 2": "",
      "HP": 55,
      "Attack": 70,
      "Defense": 45,
      "Sp. Atk": 70,
      "Sp. Def": 50,
      "Speed": 60,
      "Total": 350
    },
    {
      "Number": 59,
      "Name": "Arcanine",
      "Type 1": "Fire",
      "Type 2": "",
      "HP": 90,
      "Attack": 110,
      "Defense": 80,
      "Sp. Atk": 100,
      "Sp. Def": 80,
      "Speed": 95,
      "Total": 555
    },
    {
      "Number": 60,
      "Name": "Poliwag",
      "Type 1": "Water",
      "Type 2": "",
      "HP": 40,
      "Attack": 50,
      "Defense": 40,
      "Sp. Atk": 40,
      "Sp. Def": 40,
      "Speed": 90,
      "Total": 300
    },
    {
      "Number": 61,
      "Name": "Poliwhirl",
      "Type 1": "Water",
      "Type 2": "",
      "HP": 65,
      "Attack": 65,
      "Defense": 65,
      "Sp. Atk": 50,
      "Sp. Def": 50,
      "Speed": 90,
      "Total": 385
    },
    {
      "Number": 62,
      "Name": "Poliwrath",
      "Type 1": "Water",
      "Type 2": "Fighting",
      "HP": 90,
      "Attack": 85,
      "Defense": 95,
      "Sp. Atk": 70,
      "Sp. Def": 90,
      "Speed": 70,
      "Total": 500
    },
    {
      "Number": 63,
      "Name": "Abra",
      "Type 1": "Psychic",
      "Type 2": "",
      "HP": 25,
      "Attack": 20,
      "Defense": 15,
      "Sp. Atk": 105,
      "Sp. Def": 55,
      "Speed": 90,
      "Total": 310
    },
    {
      "Number": 64,
      "Name": "Kadabra",
      "Type 1": "Psychic",
      "Type 2": "",
      "HP": 40,
      "Attack": 35,
      "Defense": 30,
      "Sp. Atk": 120,
      "Sp. Def": 70,
      "Speed": 105,
      "Total": 400
    },
    {
      "Number": 65,
      "Name": "Alakazam",
      "Type 1": "Psychic",
      "Type 2": "",
      "HP": 55,
      "Attack": 50,
      "Defense": 45,
      "Sp. Atk": 135,
      "Sp. Def": 85,
      "Speed": 120,
      "Total": 490
    },
    {
      "Number": 66,
      "Name": "Machop",
      "Type 1": "Fighting",
      "Type 2": "",
      "HP": 70,
      "Attack": 80,
      "Defense": 50,
      "Sp. Atk": 35,
      "Sp. Def": 35,
      "Speed": 35,
      "Total": 305
    },
    {
      "Number": 67,
      "Name": "Machoke",
      "Type 1": "Fighting",
      "Type 2": "",
      "HP": 80,
      "Attack": 100,
      "Defense": 70,
      "Sp. Atk": 50,
      "Sp. Def": 60,
      "Speed": 45,
      "Total": 405
    },
    {
      "Number": 68,
      "Name": "Machamp",
      "Type 1": "Fighting",
      "Type 2": "",
      "HP": 90,
      "Attack": 130,
      "Defense": 80,
      "Sp. Atk": 65,
      "Sp. Def": 85,
      "Speed": 55,
      "Total": 505
    },
    {
      "Number": 69,
      "Name": "Bellsprout",
      "Type 1": "Grass",
      "Type 2": "Poison",
      "HP": 50,
      "Attack": 75,
      "Defense": 35,
      "Sp. Atk": 70,
      "Sp. Def": 30,
      "Speed": 40,
      "Total": 300
    },
    {
      "Number": 70,
      "Name": "Weepinbell",
      "Type 1": "Grass",
      "Type 2": "Poison",
      "HP": 65,
      "Attack": 90,
      "Defense": 50,
      "Sp. Atk": 85,
      "Sp. Def": 45,
      "Speed": 55,
      "Total": 390
    },
    {
      "Number": 71,
      "Name": "Victreebel",
      "Type 1": "Grass",
      "Type 2": "Poison",
      "HP": 80,
      "Attack": 105,
      "Defense": 65,
      "Sp. Atk": 100,
      "Sp. Def": 60,
      "Speed": 70,
      "Total": 480
    },
    {
      "Number": 72,
      "Name": "Tentacool",
      "Type 1": "Water",
      "Type 2": "Poison",
      "HP": 40,
      "Attack": 40,
      "Defense": 35,
      "Sp. Atk": 50,
      "Sp. Def": 100,
      "Speed": 70,
      "Total": 335
    },
    {
      "Number": 73,
      "Name": "Tentacruel",
      "Type 1": "Water",
      "Type 2": "Poison",
      "HP": 80,
      "Attack": 70,
      "Defense": 65,
      "Sp. Atk": 80,
      "Sp. Def": 120,
      "Speed": 100,
      "Total": 515
    },
    {
      "Number": 74,
      "Name": "Geodude",
      "Type 1": "Rock",
      "Type 2": "Ground",
      "HP": 40,
      "Attack": 80,
      "Defense": 100,
      "Sp. Atk": 30,
      "Sp. Def": 30,
      "Speed": 20,
      "Total": 300
    },
    {
      "Number": 75,
      "Name": "Graveler",
      "Type 1": "Rock",
      "Type 2": "Ground",
      "HP": 55,
      "Attack": 95,
      "Defense": 115,
      "Sp. Atk": 45,
      "Sp. Def": 45,
      "Speed": 35,
      "Total": 390
    },
    {
      "Number": 76,
      "Name": "Golem",
      "Type 1": "Rock",
      "Type 2": "Ground",
      "HP": 80,
      "Attack": 110,
      "Defense": 130,
      "Sp. Atk": 55,
      "Sp. Def": 65,
      "Speed": 45,
      "Total": 485
    },
    {
      "Number": 77,
      "Name": "Ponyta",
      "Type 1": "Fire",
      "Type 2": "",
      "HP": 50,
      "Attack": 85,
      "Defense": 55,
      "Sp. Atk": 65,
      "Sp. Def": 65,
      "Speed": 90,
      "Total": 410
    },
    {
      "Number": 78,
      "Name": "Rapidash",
      "Type 1": "Fire",
      "Type 2": "",
      "HP": 65,
      "Attack": 100,
      "Defense": 70,
      "Sp. Atk": 80,
      "Sp. Def": 80,
      "Speed": 105,
      "Total": 500
    },
    {
      "Number": 79,
      "Name": "Slowpoke",
      "Type 1": "Water",
      "Type 2": "Psychic",
      "HP": 90,
      "Attack": 65,
      "Defense": 65,
      "Sp. Atk": 40,
      "Sp. Def": 40,
      "Speed": 15,
      "Total": 315
    },
    {
      "Number": 80,
      "Name": "Slowbro",
      "Type 1": "Water",
      "Type 2": "Psychic",
      "HP": 95,
      "Attack": 75,
      "Defense": 110,
      "Sp. Atk": 100,
      "Sp. Def": 80,
      "Speed": 30,
      "Total": 490
    },
    {
      "Number": 81,
      "Name": "Magnemite",
      "Type 1": "Electric",
      "Type 2": "Steel",
      "HP": 25,
      "Attack": 35,
      "Defense": 70,
      "Sp. Atk": 95,
      "Sp. Def": 55,
      "Speed": 45,
      "Total": 325
    },
    {
      "Number": 82,
      "Name": "Magneton",
      "Type 1": "Electric",
      "Type 2": "Steel",
      "HP": 50,
      "Attack": 60,
      "Defense": 95,
      "Sp. Atk": 120,
      "Sp. Def": 70,
      "Speed": 70,
      "Total": 465
    },
    {
      "Number": 83,
      "Name": "Farfetch'd",
      "Type 1": "Normal",
      "Type 2": "Flying",
      "HP": 52,
      "Attack": 65,
      "Defense": 55,
      "Sp. Atk": 58,
      "Sp. Def": 62,
      "Speed": 60,
      "Total": 352
    },
    {
      "Number": 84,
      "Name": "Doduo",
      "Type 1": "Normal",
      "Type 2": "Flying",
      "HP": 35,
      "Attack": 85,
      "Defense": 45,
      "Sp. Atk": 35,
      "Sp. Def": 35,
      "Speed": 75,
      "Total": 310
    },
    {
      "Number": 85,
      "Name": "Dodrio",
      "Type 1": "Normal",
      "Type 2": "Flying",
      "HP": 60,
      "Attack": 110,
      "Defense": 70,
      "Sp. Atk": 60,
      "Sp. Def": 60,
      "Speed": 100,
      "Total": 460
    },
    {
      "Number": 86,
      "Name": "Seel",
      "Type 1": "Water",
      "Type 2": "",
      "HP": 65,
      "Attack": 45,
      "Defense": 55,
      "Sp. Atk": 45,
      "Sp. Def": 70,
      "Speed": 45,
      "Total": 325
    },
    {
      "Number": 87,
      "Name": "Dewgong",
      "Type 1": "Water",
      "Type 2": "Ice",
      "HP": 90,
      "Attack": 70,
      "Defense": 80,
      "Sp. Atk": 70,
      "Sp. Def": 95,
      "Speed": 70,
      "Total": 475
    },
    {
      "Number": 88,
      "Name": "Grimer",
      "Type 1": "Poison",
      "Type 2": "",
      "HP": 80,
      "Attack": 80,
      "Defense": 50,
      "Sp. Atk": 40,
      "Sp. Def": 50,
      "Speed": 25,
      "Total": 325
    },
    {
      "Number": 89,
      "Name": "Muk",
      "Type 1": "Poison",
      "Type 2": "",
      "HP": 105,
      "Attack": 105,
      "Defense": 75,
      "Sp. Atk": 65,
      "Sp. Def": 100,
      "Speed": 50,
      "Total": 500
    },
    {
      "Number": 90,
      "Name": "Shellder",
      "Type 1": "Water",
      "Type 2": "",
      "HP": 30,
      "Attack": 65,
      "Defense": 100,
      "Sp. Atk": 45,
      "Sp. Def": 25,
      "Speed": 40,
      "Total": 305
    },
    {
      "Number": 91,
      "Name": "Cloyster",
      "Type 1": "Water",
      "Type 2": "Ice",
      "HP": 50,
      "Attack": 95,
      "Defense": 180,
      "Sp. Atk": 85,
      "Sp. Def": 45,
      "Speed": 70,
      "Total": 525
    },
    {
      "Number": 92,
      "Name": "Gastly",
      "Type 1": "Ghost",
      "Type 2": "Poison",
      "HP": 30,
      "Attack": 35,
      "Defense": 30,
      "Sp. Atk": 100,
      "Sp. Def": 35,
      "Speed": 80,
      "Total": 310
    },
    {
      "Number": 93,
      "Name": "Haunter",
      "Type 1": "Ghost",
      "Type 2": "Poison",
      "HP": 45,
      "Attack": 50,
      "Defense": 45,
      "Sp. Atk": 115,
      "Sp. Def": 55,
      "Speed": 95,
      "Total": 405
    },
    {
      "Number": 94,
      "Name": "Gengar",
      "Type 1": "Ghost",
      "Type 2": "Poison",
      "HP": 60,
      "Attack": 65,
      "Defense": 60,
      "Sp. Atk": 130,
      "Sp. Def": 75,
      "Speed": 110,
      "Total": 500
    },
    {
      "Number": 95,
      "Name": "Onix",
      "Type 1": "Rock",
      "Type 2": "Ground",
      "HP": 35,
      "Attack": 45,
      "Defense": 160,
      "Sp. Atk": 30,
      "Sp. Def": 45,
      "Speed": 70,
      "Total": 385
    },
    {
      "Number": 96,
      "Name": "Drowzee",
      "Type 1": "Psychic",
      "Type 2": "",
      "HP": 60,
      "Attack": 48,
      "Defense": 45,
      "Sp. Atk": 43,
      "Sp. Def": 90,
      "Speed": 42,
      "Total": 328
    },
    {
      "Number": 97,
      "Name": "Hypno",
      "Type 1": "Psychic",
      "Type 2": "",
      "HP": 85,
      "Attack": 73,
      "Defense": 70,
      "Sp. Atk": 73,
      "Sp. Def": 115,
      "Speed": 67,
      "Total": 483
    },
    {
      "Number": 98,
      "Name": "Krabby",
      "Type 1": "Water",
      "Type 2": "",
      "HP": 30,
      "Attack": 105,
      "Defense": 90,
      "Sp. Atk": 25,
      "Sp. Def": 25,
      "Speed": 50,
      "Total": 325
    },
    {
      "Number": 99,
      "Name": "Kingler",
      "Type 1": "Water",
      "Type 2": "",
      "HP": 55,
      "Attack": 130,
      "Defense": 115,
      "Sp. Atk": 50,
      "Sp. Def": 50,
      "Speed": 75,
      "Total": 475
    },
    {
      "Number": 100,
      "Name": "Voltorb",
      "Type 1": "Electric",
      "Type 2": "",
      "HP": 40,
      "Attack": 30,
      "Defense": 50,
      "Sp. Atk": 55,
      "Sp. Def": 55,
      "Speed": 100,
      "Total": 330
    },
    {
      "Number": 101,
      "Name": "Electrode",
      "Type 1": "Electric",
      "Type 2": "",
      "HP": 60,
      "Attack": 50,
      "Defense": 70,
      "Sp. Atk": 80,
      "Sp. Def": 80,
      "Speed": 140,
      "Total": 480
    },
    {
      "Number": 102,
      "Name": "Exeggcute",
      "Type 1": "Grass",
      "Type 2": "Psychic",
      "HP": 60,
      "Attack": 40,
      "Defense": 80,
      "Sp. Atk": 60,
      "Sp. Def": 45,
      "Speed": 40,
      "Total": 325
    },
    {
      "Number": 103,
      "Name": "Exeggutor",
      "Type 1": "Grass",
      "Type 2": "Psychic",
      "HP": 95,
      "Attack": 95,
      "Defense": 85,
      "Sp. Atk": 125,
      "Sp. Def": 65,
      "Speed": 55,
      "Total": 520
    },
    {
      "Number": 104,
      "Name": "Cubone",
      "Type 1": "Ground",
      "Type 2": "",
      "HP": 50,
      "Attack": 50,
      "Defense": 95,
      "Sp. Atk": 40,
      "Sp. Def": 50,
      "Speed": 35,
      "Total": 320
    },
    {
      "Number": 105,
      "Name": "Marowak",
      "Type 1": "Ground",
      "Type 2": "",
      "HP": 60,
      "Attack": 80,
      "Defense": 110,
      "Sp. Atk": 50,
      "Sp. Def": 80,
      "Speed": 45,
      "Total": 425
    },
    {
      "Number": 106,
      "Name": "Hitmonlee",
      "Type 1": "Fighting",
      "Type 2": "",
      "HP": 50,
      "Attack": 120,
      "Defense": 53,
      "Sp. Atk": 35,
      "Sp. Def": 110,
      "Speed": 87,
      "Total": 455
    },
    {
      "Number": 107,
      "Name": "Hitmonchan",
      "Type 1": "Fighting",
      "Type 2": "",
      "HP": 50,
      "Attack": 105,
      "Defense": 79,
      "Sp. Atk": 35,
      "Sp. Def": 110,
      "Speed": 76,
      "Total": 455
    },
    {
      "Number": 108,
      "Name": "Licktung",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 90,
      "Attack": 55,
      "Defense": 75,
      "Sp. Atk": 60,
      "Sp. Def": 75,
      "Speed": 30,
      "Total": 385
    },
    {
      "Number": 109,
      "Name": "Koffing",
      "Type 1": "Poison",
      "Type 2": "",
      "HP": 40,
      "Attack": 65,
      "Defense": 95,
      "Sp. Atk": 60,
      "Sp. Def": 45,
      "Speed": 35,
      "Total": 340
    },
    {
      "Number": 110,
      "Name": "Weezing",
      "Type 1": "Poison",
      "Type 2": "",
      "HP": 65,
      "Attack": 90,
      "Defense": 120,
      "Sp. Atk": 85,
      "Sp. Def": 70,
      "Speed": 60,
      "Total": 490
    },
    {
      "Number": 111,
      "Name": "Rhyhorn",
      "Type 1": "Ground",
      "Type 2": "Rock",
      "HP": 80,
      "Attack": 85,
      "Defense": 95,
      "Sp. Atk": 30,
      "Sp. Def": 30,
      "Speed": 25,
      "Total": 345
    },
    {
      "Number": 112,
      "Name": "Rhydon",
      "Type 1": "Ground",
      "Type 2": "Rock",
      "HP": 105,
      "Attack": 130,
      "Defense": 120,
      "Sp. Atk": 45,
      "Sp. Def": 45,
      "Speed": 40,
      "Total": 485
    },
    {
      "Number": 113,
      "Name": "Chansey",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 250,
      "Attack": 5,
      "Defense": 5,
      "Sp. Atk": 35,
      "Sp. Def": 105,
      "Speed": 50,
      "Total": 450
    },
    {
      "Number": 114,
      "Name": "Tangela",
      "Type 1": "Grass",
      "Type 2": "",
      "HP": 65,
      "Attack": 55,
      "Defense": 115,
      "Sp. Atk": 100,
      "Sp. Def": 40,
      "Speed": 60,
      "Total": 435
    },
    {
      "Number": 115,
      "Name": "Kangaskhan",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 105,
      "Attack": 95,
      "Defense": 80,
      "Sp. Atk": 40,
      "Sp. Def": 80,
      "Speed": 90,
      "Total": 490
    },
    {
      "Number": 116,
      "Name": "Horsea",
      "Type 1": "Water",
      "Type 2": "",
      "HP": 30,
      "Attack": 40,
      "Defense": 70,
      "Sp. Atk": 70,
      "Sp. Def": 25,
      "Speed": 60,
      "Total": 295
    },
    {
      "Number": 117,
      "Name": "Seadra",
      "Type 1": "Water",
      "Type 2": "",
      "HP": 55,
      "Attack": 65,
      "Defense": 95,
      "Sp. Atk": 95,
      "Sp. Def": 45,
      "Speed": 85,
      "Total": 440
    },
    {
      "Number": 118,
      "Name": "Goldeen",
      "Type 1": "Water",
      "Type 2": "",
      "HP": 45,
      "Attack": 67,
      "Defense": 60,
      "Sp. Atk": 35,
      "Sp. Def": 50,
      "Speed": 63,
      "Total": 320
    },
    {
      "Number": 119,
      "Name": "Seaking",
      "Type 1": "Water",
      "Type 2": "",
      "HP": 80,
      "Attack": 92,
      "Defense": 65,
      "Sp. Atk": 65,
      "Sp. Def": 80,
      "Speed": 68,
      "Total": 450
    },
    {
      "Number": 120,
      "Name": "Staryu",
      "Type 1": "Water",
      "Type 2": "",
      "HP": 30,
      "Attack": 45,
      "Defense": 55,
      "Sp. Atk": 70,
      "Sp. Def": 55,
      "Speed": 85,
      "Total": 340
    },
    {
      "Number": 121,
      "Name": "Starmie",
      "Type 1": "Water",
      "Type 2": "Psychic",
      "HP": 60,
      "Attack": 75,
      "Defense": 85,
      "Sp. Atk": 100,
      "Sp. Def": 85,
      "Speed": 115,
      "Total": 520
    },
    {
      "Number": 122,
      "Name": "Mr. Mime",
      "Type 1": "Psychic",
      "Type 2": "",
      "HP": 40,
      "Attack": 45,
      "Defense": 65,
      "Sp. Atk": 100,
      "Sp. Def": 120,
      "Speed": 90,
      "Total": 460
    },
    {
      "Number": 123,
      "Name": "Scyther",
      "Type 1": "Bug",
      "Type 2": "Flying",
      "HP": 70,
      "Attack": 110,
      "Defense": 80,
      "Sp. Atk": 55,
      "Sp. Def": 80,
      "Speed": 105,
      "Total": 500
    },
    {
      "Number": 124,
      "Name": "Jinx",
      "Type 1": "Ice",
      "Type 2": "Psychic",
      "HP": 65,
      "Attack": 50,
      "Defense": 35,
      "Sp. Atk": 115,
      "Sp. Def": 95,
      "Speed": 95,
      "Total": 455
    },
    {
      "Number": 125,
      "Name": "Electabuzz",
      "Type 1": "Electric",
      "Type 2": "",
      "HP": 65,
      "Attack": 83,
      "Defense": 57,
      "Sp. Atk": 95,
      "Sp. Def": 85,
      "Speed": 105,
      "Total": 490
    },
    {
      "Number": 126,
      "Name": "Magmar",
      "Type 1": "Fire",
      "Type 2": "",
      "HP": 65,
      "Attack": 95,
      "Defense": 57,
      "Sp. Atk": 100,
      "Sp. Def": 85,
      "Speed": 93,
      "Total": 495
    },
    {
      "Number": 127,
      "Name": "Pinsir",
      "Type 1": "Bug",
      "Type 2": "",
      "HP": 65,
      "Attack": 125,
      "Defense": 100,
      "Sp. Atk": 55,
      "Sp. Def": 70,
      "Speed": 85,
      "Total": 500
    },
    {
      "Number": 128,
      "Name": "Tauros",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 75,
      "Attack": 100,
      "Defense": 95,
      "Sp. Atk": 40,
      "Sp. Def": 70,
      "Speed": 110,
      "Total": 490
    },
    {
      "Number": 129,
      "Name": "Magikarp",
      "Type 1": "Water",
      "Type 2": "",
      "HP": 20,
      "Attack": 10,
      "Defense": 55,
      "Sp. Atk": 15,
      "Sp. Def": 20,
      "Speed": 80,
      "Total": 200
    },
    {
      "Number": 130,
      "Name": "Gyarados",
      "Type 1": "Water",
      "Type 2": "Flying",
      "HP": 95,
      "Attack": 125,
      "Defense": 79,
      "Sp. Atk": 60,
      "Sp. Def": 100,
      "Speed": 81,
      "Total": 540
    },
    {
      "Number": 131,
      "Name": "Lapras",
      "Type 1": "Water",
      "Type 2": "Ice",
      "HP": 130,
      "Attack": 85,
      "Defense": 80,
      "Sp. Atk": 85,
      "Sp. Def": 95,
      "Speed": 60,
      "Total": 535
    },
    {
      "Number": 132,
      "Name": "Ditto",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 48,
      "Attack": 48,
      "Defense": 48,
      "Sp. Atk": 48,
      "Sp. Def": 48,
      "Speed": 48,
      "Total": 288
    },
    {
      "Number": 133,
      "Name": "Eevee",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 55,
      "Attack": 55,
      "Defense": 50,
      "Sp. Atk": 45,
      "Sp. Def": 65,
      "Speed": 55,
      "Total": 325
    },
    {
      "Number": 134,
      "Name": "Vaporeon",
      "Type 1": "Water",
      "Type 2": "",
      "HP": 130,
      "Attack": 65,
      "Defense": 60,
      "Sp. Atk": 110,
      "Sp. Def": 95,
      "Speed": 65,
      "Total": 525
    },
    {
      "Number": 135,
      "Name": "Jolteon",
      "Type 1": "Electric",
      "Type 2": "",
      "HP": 65,
      "Attack": 65,
      "Defense": 60,
      "Sp. Atk": 110,
      "Sp. Def": 95,
      "Speed": 130,
      "Total": 525
    },
    {
      "Number": 136,
      "Name": "Flareon",
      "Type 1": "Fire",
      "Type 2": "",
      "HP": 65,
      "Attack": 130,
      "Defense": 60,
      "Sp. Atk": 95,
      "Sp. Def": 110,
      "Speed": 65,
      "Total": 525
    },
    {
      "Number": 137,
      "Name": "Porygon",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 65,
      "Attack": 60,
      "Defense": 70,
      "Sp. Atk": 85,
      "Sp. Def": 75,
      "Speed": 40,
      "Total": 395
    },
    {
      "Number": 138,
      "Name": "Omanyte",
      "Type 1": "Rock",
      "Type 2": "Water",
      "HP": 35,
      "Attack": 40,
      "Defense": 100,
      "Sp. Atk": 90,
      "Sp. Def": 55,
      "Speed": 35,
      "Total": 355
    },
    {
      "Number": 139,
      "Name": "Omastar",
      "Type 1": "Rock",
      "Type 2": "Water",
      "HP": 70,
      "Attack": 60,
      "Defense": 125,
      "Sp. Atk": 115,
      "Sp. Def": 70,
      "Speed": 55,
      "Total": 495
    },
    {
      "Number": 140,
      "Name": "Kabuto",
      "Type 1": "Rock",
      "Type 2": "Water",
      "HP": 30,
      "Attack": 80,
      "Defense": 90,
      "Sp. Atk": 55,
      "Sp. Def": 45,
      "Speed": 55,
      "Total": 355
    },
    {
      "Number": 141,
      "Name": "Kabutops",
      "Type 1": "Rock",
      "Type 2": "Water",
      "HP": 60,
      "Attack": 115,
      "Defense": 105,
      "Sp. Atk": 65,
      "Sp. Def": 70,
      "Speed": 80,
      "Total": 495
    },
    {
      "Number": 142,
      "Name": "Aerodactyl",
      "Type 1": "Rock",
      "Type 2": "Flying",
      "HP": 80,
      "Attack": 105,
      "Defense": 65,
      "Sp. Atk": 60,
      "Sp. Def": 75,
      "Speed": 130,
      "Total": 515
    },
    {
      "Number": 143,
      "Name": "Snorlax",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 160,
      "Attack": 110,
      "Defense": 65,
      "Sp. Atk": 65,
      "Sp. Def": 110,
      "Speed": 30,
      "Total": 540
    },
    {
      "Number": 144,
      "Name": "Articuno",
      "Type 1": "Ice",
      "Type 2": "Flying",
      "HP": 90,
      "Attack": 85,
      "Defense": 100,
      "Sp. Atk": 95,
      "Sp. Def": 125,
      "Speed": 85,
      "Total": 580
    },
    {
      "Number": 145,
      "Name": "Zapdos",
      "Type 1": "Electric",
      "Type 2": "Flying",
      "HP": 90,
      "Attack": 90,
      "Defense": 85,
      "Sp. Atk": 125,
      "Sp. Def": 90,
      "Speed": 100,
      "Total": 580
    },
    {
      "Number": 146,
      "Name": "Moltres",
      "Type 1": "Fire",
      "Type 2": "Flying",
      "HP": 90,
      "Attack": 100,
      "Defense": 90,
      "Sp. Atk": 125,
      "Sp. Def": 85,
      "Speed": 90,
      "Total": 580
    },
    {
      "Number": 147,
      "Name": "Dratini",
      "Type 1": "Dragon",
      "Type 2": "",
      "HP": 41,
      "Attack": 64,
      "Defense": 45,
      "Sp. Atk": 50,
      "Sp. Def": 50,
      "Speed": 50,
      "Total": 300
    },
    {
      "Number": 148,
      "Name": "Dragonair",
      "Type 1": "Dragon",
      "Type 2": "",
      "HP": 61,
      "Attack": 84,
      "Defense": 65,
      "Sp. Atk": 70,
      "Sp. Def": 70,
      "Speed": 70,
      "Total": 420
    },
    {
      "Number": 149,
      "Name": "Dragonite",
      "Type 1": "Dragon",
      "Type 2": "Flying",
      "HP": 91,
      "Attack": 134,
      "Defense": 95,
      "Sp. Atk": 100,
      "Sp. Def": 100,
      "Speed": 80,
      "Total": 600
    },
    {
      "Number": 150,
      "Name": "Mewtwo",
      "Type 1": "Psychic",
      "Type 2": "",
      "HP": 106,
      "Attack": 110,
      "Defense": 90,
      "Sp. Atk": 154,
      "Sp. Def": 90,
      "Speed": 130,
      "Total": 680
    },
    {
      "Number": 151,
      "Name": "Mew",
      "Type 1": "Psychic",
      "Type 2": "",
      "HP": 100,
      "Attack": 100,
      "Defense": 100,
      "Sp. Atk": 100,
      "Sp. Def": 100,
      "Speed": 100,
      "Total": 600
    },
    {
      "Number": 152,
      "Name": "Chikorita",
      "Type 1": "Grass",
      "Type 2": "",
      "HP": 45,
      "Attack": 49,
      "Defense": 65,
      "Sp. Atk": 49,
      "Sp. Def": 65,
      "Speed": 45,
      "Total": 318
    },
    {
      "Number": 153,
      "Name": "Bayleef",
      "Type 1": "Grass",
      "Type 2": "",
      "HP": 60,
      "Attack": 62,
      "Defense": 80,
      "Sp. Atk": 63,
      "Sp. Def": 80,
      "Speed": 60,
      "Total": 405
    },
    {
      "Number": 154,
      "Name": "Meganium",
      "Type 1": "Grass",
      "Type 2": "",
      "HP": 80,
      "Attack": 82,
      "Defense": 100,
      "Sp. Atk": 83,
      "Sp. Def": 100,
      "Speed": 80,
      "Total": 525
    },
    {
      "Number": 155,
      "Name": "Cyndaquil",
      "Type 1": "Fire",
      "Type 2": "",
      "HP": 39,
      "Attack": 52,
      "Defense": 43,
      "Sp. Atk": 60,
      "Sp. Def": 50,
      "Speed": 65,
      "Total": 309
    },
    {
      "Number": 156,
      "Name": "Quilava",
      "Type 1": "Fire",
      "Type 2": "",
      "HP": 58,
      "Attack": 64,
      "Defense": 58,
      "Sp. Atk": 80,
      "Sp. Def": 65,
      "Speed": 80,
      "Total": 405
    },
    {
      "Number": 157,
      "Name": "Typhlosion",
      "Type 1": "Fire",
      "Type 2": "",
      "HP": 78,
      "Attack": 84,
      "Defense": 78,
      "Sp. Atk": 109,
      "Sp. Def": 85,
      "Speed": 100,
      "Total": 534
    },
    {
      "Number": 158,
      "Name": "Totodile",
      "Type 1": "Water",
      "Type 2": "",
      "HP": 50,
      "Attack": 65,
      "Defense": 64,
      "Sp. Atk": 44,
      "Sp. Def": 48,
      "Speed": 43,
      "Total": 314
    },
    {
      "Number": 159,
      "Name": "Croconaw",
      "Type 1": "Water",
      "Type 2": "",
      "HP": 65,
      "Attack": 80,
      "Defense": 80,
      "Sp. Atk": 59,
      "Sp. Def": 63,
      "Speed": 58,
      "Total": 405
    },
    {
      "Number": 160,
      "Name": "Feraligatr",
      "Type 1": "Water",
      "Type 2": "",
      "HP": 85,
      "Attack": 105,
      "Defense": 100,
      "Sp. Atk": 79,
      "Sp. Def": 83,
      "Speed": 78,
      "Total": 530
    },
    {
      "Number": 161,
      "Name": "Sentret",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 35,
      "Attack": 46,
      "Defense": 34,
      "Sp. Atk": 35,
      "Sp. Def": 45,
      "Speed": 20,
      "Total": 215
    },
    {
      "Number": 162,
      "Name": "Furret",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 85,
      "Attack": 76,
      "Defense": 64,
      "Sp. Atk": 45,
      "Sp. Def": 55,
      "Speed": 90,
      "Total": 415
    },
    {
      "Number": 163,
      "Name": "Hoothoot",
      "Type 1": "Normal",
      "Type 2": "Flying",
      "HP": 60,
      "Attack": 30,
      "Defense": 30,
      "Sp. Atk": 36,
      "Sp. Def": 56,
      "Speed": 50,
      "Total": 262
    },
    {
      "Number": 164,
      "Name": "Noctowl",
      "Type 1": "Normal",
      "Type 2": "Flying",
      "HP": 100,
      "Attack": 50,
      "Defense": 50,
      "Sp. Atk": 76,
      "Sp. Def": 96,
      "Speed": 70,
      "Total": 442
    },
    {
      "Number": 165,
      "Name": "Ledyba",
      "Type 1": "Bug",
      "Type 2": "Flying",
      "HP": 40,
      "Attack": 20,
      "Defense": 30,
      "Sp. Atk": 40,
      "Sp. Def": 80,
      "Speed": 55,
      "Total": 265
    },
    {
      "Number": 166,
      "Name": "Ledian",
      "Type 1": "Bug",
      "Type 2": "Flying",
      "HP": 55,
      "Attack": 35,
      "Defense": 50,
      "Sp. Atk": 55,
      "Sp. Def": 110,
      "Speed": 85,
      "Total": 390
    },
    {
      "Number": 167,
      "Name": "Spinarak",
      "Type 1": "Bug",
      "Type 2": "Poison",
      "HP": 40,
      "Attack": 60,
      "Defense": 40,
      "Sp. Atk": 40,
      "Sp. Def": 40,
      "Speed": 30,
      "Total": 250
    },
    {
      "Number": 168,
      "Name": "Ariados",
      "Type 1": "Bug",
      "Type 2": "Poison",
      "HP": 70,
      "Attack": 90,
      "Defense": 70,
      "Sp. Atk": 60,
      "Sp. Def": 60,
      "Speed": 40,
      "Total": 390
    },
    {
      "Number": 169,
      "Name": "Crobat",
      "Type 1": "Poison",
      "Type 2": "Flying",
      "HP": 85,
      "Attack": 90,
      "Defense": 80,
      "Sp. Atk": 70,
      "Sp. Def": 80,
      "Speed": 130,
      "Total": 535
    },
    {
      "Number": 170,
      "Name": "Chinchou",
      "Type 1": "Water",
      "Type 2": "Electric",
      "HP": 75,
      "Attack": 38,
      "Defense": 38,
      "Sp. Atk": 56,
      "Sp. Def": 56,
      "Speed": 67,
      "Total": 330
    },
    {
      "Number": 171,
      "Name": "Lanturn",
      "Type 1": "Water",
      "Type 2": "Electric",
      "HP": 125,
      "Attack": 58,
      "Defense": 58,
      "Sp. Atk": 76,
      "Sp. Def": 76,
      "Speed": 67,
      "Total": 460
    },
    {
      "Number": 172,
      "Name": "Pichu",
      "Type 1": "Electric",
      "Type 2": "",
      "HP": 20,
      "Attack": 40,
      "Defense": 15,
      "Sp. Atk": 35,
      "Sp. Def": 35,
      "Speed": 60,
      "Total": 205
    },
    {
      "Number": 173,
      "Name": "Cleffa",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 50,
      "Attack": 25,
      "Defense": 28,
      "Sp. Atk": 45,
      "Sp. Def": 55,
      "Speed": 15,
      "Total": 218
    },
    {
      "Number": 174,
      "Name": "Igglybuff",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 90,
      "Attack": 30,
      "Defense": 15,
      "Sp. Atk": 40,
      "Sp. Def": 20,
      "Speed": 15,
      "Total": 210
    },
    {
      "Number": 175,
      "Name": "Togepi",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 35,
      "Attack": 20,
      "Defense": 65,
      "Sp. Atk": 40,
      "Sp. Def": 65,
      "Speed": 20,
      "Total": 245
    },
    {
      "Number": 176,
      "Name": "Togetic",
      "Type 1": "Normal",
      "Type 2": "Flying",
      "HP": 55,
      "Attack": 40,
      "Defense": 85,
      "Sp. Atk": 80,
      "Sp. Def": 105,
      "Speed": 40,
      "Total": 405
    },
    {
      "Number": 177,
      "Name": "Natu",
      "Type 1": "Psychic",
      "Type 2": "Flying",
      "HP": 40,
      "Attack": 50,
      "Defense": 45,
      "Sp. Atk": 70,
      "Sp. Def": 45,
      "Speed": 70,
      "Total": 320
    },
    {
      "Number": 178,
      "Name": "Xatu",
      "Type 1": "Psychic",
      "Type 2": "Flying",
      "HP": 65,
      "Attack": 75,
      "Defense": 70,
      "Sp. Atk": 95,
      "Sp. Def": 70,
      "Speed": 95,
      "Total": 470
    },
    {
      "Number": 179,
      "Name": "Mareep",
      "Type 1": "Electric",
      "Type 2": "",
      "HP": 55,
      "Attack": 40,
      "Defense": 40,
      "Sp. Atk": 65,
      "Sp. Def": 45,
      "Speed": 35,
      "Total": 280
    },
    {
      "Number": 180,
      "Name": "Flaafy",
      "Type 1": "Electric",
      "Type 2": "",
      "HP": 70,
      "Attack": 55,
      "Defense": 55,
      "Sp. Atk": 80,
      "Sp. Def": 60,
      "Speed": 45,
      "Total": 365
    },
    {
      "Number": 181,
      "Name": "Ampharos",
      "Type 1": "Electric",
      "Type 2": "",
      "HP": 90,
      "Attack": 75,
      "Defense": 75,
      "Sp. Atk": 115,
      "Sp. Def": 90,
      "Speed": 55,
      "Total": 500
    },
    {
      "Number": 182,
      "Name": "Bellossom",
      "Type 1": "Grass",
      "Type 2": "",
      "HP": 75,
      "Attack": 80,
      "Defense": 85,
      "Sp. Atk": 90,
      "Sp. Def": 100,
      "Speed": 50,
      "Total": 480
    },
    {
      "Number": 183,
      "Name": "Marill",
      "Type 1": "Water",
      "Type 2": "",
      "HP": 70,
      "Attack": 20,
      "Defense": 50,
      "Sp. Atk": 20,
      "Sp. Def": 50,
      "Speed": 40,
      "Total": 250
    },
    {
      "Number": 184,
      "Name": "Azumarill",
      "Type 1": "Water",
      "Type 2": "",
      "HP": 100,
      "Attack": 50,
      "Defense": 80,
      "Sp. Atk": 50,
      "Sp. Def": 80,
      "Speed": 50,
      "Total": 410
    },
    {
      "Number": 185,
      "Name": "Sudowoodo",
      "Type 1": "Rock",
      "Type 2": "",
      "HP": 70,
      "Attack": 100,
      "Defense": 115,
      "Sp. Atk": 30,
      "Sp. Def": 65,
      "Speed": 30,
      "Total": 410
    },
    {
      "Number": 186,
      "Name": "Politoad",
      "Type 1": "Water",
      "Type 2": "",
      "HP": 90,
      "Attack": 75,
      "Defense": 75,
      "Sp. Atk": 90,
      "Sp. Def": 100,
      "Speed": 70,
      "Total": 500
    },
    {
      "Number": 187,
      "Name": "Hoppip",
      "Type 1": "Grass",
      "Type 2": "Flying",
      "HP": 35,
      "Attack": 35,
      "Defense": 40,
      "Sp. Atk": 35,
      "Sp. Def": 55,
      "Speed": 50,
      "Total": 250
    },
    {
      "Number": 188,
      "Name": "Skiploom",
      "Type 1": "Grass",
      "Type 2": "Flying",
      "HP": 55,
      "Attack": 45,
      "Defense": 50,
      "Sp. Atk": 45,
      "Sp. Def": 65,
      "Speed": 80,
      "Total": 340
    },
    {
      "Number": 189,
      "Name": "Jumpluff",
      "Type 1": "Grass",
      "Type 2": "Flying",
      "HP": 75,
      "Attack": 55,
      "Defense": 70,
      "Sp. Atk": 55,
      "Sp. Def": 85,
      "Speed": 110,
      "Total": 450
    },
    {
      "Number": 190,
      "Name": "Aipom",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 55,
      "Attack": 70,
      "Defense": 55,
      "Sp. Atk": 40,
      "Sp. Def": 55,
      "Speed": 85,
      "Total": 360
    },
    {
      "Number": 191,
      "Name": "Sunkern",
      "Type 1": "Grass",
      "Type 2": "",
      "HP": 30,
      "Attack": 30,
      "Defense": 30,
      "Sp. Atk": 30,
      "Sp. Def": 30,
      "Speed": 30,
      "Total": 180
    },
    {
      "Number": 192,
      "Name": "Sunflora",
      "Type 1": "Grass",
      "Type 2": "",
      "HP": 75,
      "Attack": 75,
      "Defense": 55,
      "Sp. Atk": 105,
      "Sp. Def": 85,
      "Speed": 30,
      "Total": 425
    },
    {
      "Number": 193,
      "Name": "Yanma",
      "Type 1": "Bug",
      "Type 2": "Flying",
      "HP": 65,
      "Attack": 65,
      "Defense": 45,
      "Sp. Atk": 75,
      "Sp. Def": 45,
      "Speed": 95,
      "Total": 390
    },
    {
      "Number": 194,
      "Name": "Wooper",
      "Type 1": "Water",
      "Type 2": "Ground",
      "HP": 55,
      "Attack": 45,
      "Defense": 45,
      "Sp. Atk": 25,
      "Sp. Def": 25,
      "Speed": 15,
      "Total": 210
    },
    {
      "Number": 195,
      "Name": "Quagsire",
      "Type 1": "Water",
      "Type 2": "Ground",
      "HP": 95,
      "Attack": 85,
      "Defense": 85,
      "Sp. Atk": 65,
      "Sp. Def": 65,
      "Speed": 35,
      "Total": 430
    },
    {
      "Number": 196,
      "Name": "Espeon",
      "Type 1": "Psychic",
      "Type 2": "",
      "HP": 65,
      "Attack": 65,
      "Defense": 60,
      "Sp. Atk": 130,
      "Sp. Def": 95,
      "Speed": 110,
      "Total": 525
    },
    {
      "Number": 197,
      "Name": "Umbreon",
      "Type 1": "Dark",
      "Type 2": "",
      "HP": 95,
      "Attack": 65,
      "Defense": 110,
      "Sp. Atk": 60,
      "Sp. Def": 130,
      "Speed": 65,
      "Total": 525
    },
    {
      "Number": 198,
      "Name": "Murkrow",
      "Type 1": "Dark",
      "Type 2": "Flying",
      "HP": 60,
      "Attack": 85,
      "Defense": 42,
      "Sp. Atk": 85,
      "Sp. Def": 42,
      "Speed": 91,
      "Total": 405
    },
    {
      "Number": 199,
      "Name": "Slowking",
      "Type 1": "Water",
      "Type 2": "Psychic",
      "HP": 95,
      "Attack": 75,
      "Defense": 80,
      "Sp. Atk": 100,
      "Sp. Def": 110,
      "Speed": 30,
      "Total": 490
    },
    {
      "Number": 200,
      "Name": "Misdreavus",
      "Type 1": "Ghost",
      "Type 2": "",
      "HP": 60,
      "Attack": 60,
      "Defense": 60,
      "Sp. Atk": 85,
      "Sp. Def": 85,
      "Speed": 85,
      "Total": 435
    },
    {
      "Number": 201,
      "Name": "Unown",
      "Type 1": "Psychic",
      "Type 2": "",
      "HP": 48,
      "Attack": 72,
      "Defense": 48,
      "Sp. Atk": 72,
      "Sp. Def": 48,
      "Speed": 48,
      "Total": 336
    },
    {
      "Number": 202,
      "Name": "Wobbuffet",
      "Type 1": "Psychic",
      "Type 2": "",
      "HP": 190,
      "Attack": 33,
      "Defense": 58,
      "Sp. Atk": 33,
      "Sp. Def": 58,
      "Speed": 33,
      "Total": 405
    },
    {
      "Number": 203,
      "Name": "Girafarig",
      "Type 1": "Normal",
      "Type 2": "Psychic",
      "HP": 70,
      "Attack": 80,
      "Defense": 65,
      "Sp. Atk": 90,
      "Sp. Def": 65,
      "Speed": 85,
      "Total": 455
    },
    {
      "Number": 204,
      "Name": "Pineco",
      "Type 1": "Bug",
      "Type 2": "",
      "HP": 50,
      "Attack": 65,
      "Defense": 90,
      "Sp. Atk": 35,
      "Sp. Def": 35,
      "Speed": 15,
      "Total": 290
    },
    {
      "Number": 205,
      "Name": "Forretress",
      "Type 1": "Bug",
      "Type 2": "Steel",
      "HP": 75,
      "Attack": 90,
      "Defense": 140,
      "Sp. Atk": 60,
      "Sp. Def": 60,
      "Speed": 40,
      "Total": 465
    },
    {
      "Number": 206,
      "Name": "Dunsparce",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 100,
      "Attack": 70,
      "Defense": 70,
      "Sp. Atk": 65,
      "Sp. Def": 65,
      "Speed": 45,
      "Total": 415
    },
    {
      "Number": 207,
      "Name": "Gligar",
      "Type 1": "Ground",
      "Type 2": "Flying",
      "HP": 65,
      "Attack": 75,
      "Defense": 105,
      "Sp. Atk": 35,
      "Sp. Def": 65,
      "Speed": 85,
      "Total": 430
    },
    {
      "Number": 208,
      "Name": "Steelix",
      "Type 1": "Steel",
      "Type 2": "Ground",
      "HP": 75,
      "Attack": 85,
      "Defense": 200,
      "Sp. Atk": 55,
      "Sp. Def": 65,
      "Speed": 30,
      "Total": 510
    },
    {
      "Number": 209,
      "Name": "Snubbull",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 60,
      "Attack": 80,
      "Defense": 50,
      "Sp. Atk": 40,
      "Sp. Def": 40,
      "Speed": 30,
      "Total": 300
    },
    {
      "Number": 210,
      "Name": "Granbull",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 90,
      "Attack": 120,
      "Defense": 75,
      "Sp. Atk": 60,
      "Sp. Def": 60,
      "Speed": 45,
      "Total": 450
    },
    {
      "Number": 211,
      "Name": "Qwilfish",
      "Type 1": "Water",
      "Type 2": "Poison",
      "HP": 65,
      "Attack": 95,
      "Defense": 75,
      "Sp. Atk": 55,
      "Sp. Def": 55,
      "Speed": 85,
      "Total": 430
    },
    {
      "Number": 212,
      "Name": "Scizor",
      "Type 1": "Bug",
      "Type 2": "Steel",
      "HP": 70,
      "Attack": 130,
      "Defense": 100,
      "Sp. Atk": 55,
      "Sp. Def": 80,
      "Speed": 65,
      "Total": 500
    },
    {
      "Number": 213,
      "Name": "Shuckle",
      "Type 1": "Bug",
      "Type 2": "Rock",
      "HP": 20,
      "Attack": 10,
      "Defense": 230,
      "Sp. Atk": 10,
      "Sp. Def": 230,
      "Speed": 5,
      "Total": 505
    },
    {
      "Number": 214,
      "Name": "Heracross",
      "Type 1": "Bug",
      "Type 2": "Fighting",
      "HP": 80,
      "Attack": 125,
      "Defense": 75,
      "Sp. Atk": 40,
      "Sp. Def": 95,
      "Speed": 85,
      "Total": 500
    },
    {
      "Number": 215,
      "Name": "Sneasel",
      "Type 1": "Dark",
      "Type 2": "Ice",
      "HP": 55,
      "Attack": 95,
      "Defense": 55,
      "Sp. Atk": 35,
      "Sp. Def": 75,
      "Speed": 115,
      "Total": 430
    },
    {
      "Number": 216,
      "Name": "Teddiursa",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 60,
      "Attack": 80,
      "Defense": 50,
      "Sp. Atk": 50,
      "Sp. Def": 50,
      "Speed": 40,
      "Total": 330
    },
    {
      "Number": 217,
      "Name": "Ursaring",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 90,
      "Attack": 130,
      "Defense": 75,
      "Sp. Atk": 75,
      "Sp. Def": 75,
      "Speed": 55,
      "Total": 500
    },
    {
      "Number": 218,
      "Name": "Slugma",
      "Type 1": "Fire",
      "Type 2": "",
      "HP": 40,
      "Attack": 40,
      "Defense": 40,
      "Sp. Atk": 70,
      "Sp. Def": 40,
      "Speed": 20,
      "Total": 250
    },
    {
      "Number": 219,
      "Name": "Magcargo",
      "Type 1": "Fire",
      "Type 2": "Rock",
      "HP": 50,
      "Attack": 50,
      "Defense": 120,
      "Sp. Atk": 80,
      "Sp. Def": 80,
      "Speed": 30,
      "Total": 410
    },
    {
      "Number": 220,
      "Name": "Swinub",
      "Type 1": "Ice",
      "Type 2": "Ground",
      "HP": 50,
      "Attack": 50,
      "Defense": 40,
      "Sp. Atk": 30,
      "Sp. Def": 30,
      "Speed": 50,
      "Total": 250
    },
    {
      "Number": 221,
      "Name": "Piloswine",
      "Type 1": "Ice",
      "Type 2": "Ground",
      "HP": 100,
      "Attack": 100,
      "Defense": 80,
      "Sp. Atk": 60,
      "Sp. Def": 60,
      "Speed": 50,
      "Total": 450
    },
    {
      "Number": 222,
      "Name": "Corsola",
      "Type 1": "Water",
      "Type 2": "Rock",
      "HP": 55,
      "Attack": 55,
      "Defense": 85,
      "Sp. Atk": 65,
      "Sp. Def": 85,
      "Speed": 35,
      "Total": 380
    },
    {
      "Number": 223,
      "Name": "Remoraid",
      "Type 1": "Water",
      "Type 2": "",
      "HP": 35,
      "Attack": 65,
      "Defense": 35,
      "Sp. Atk": 65,
      "Sp. Def": 35,
      "Speed": 65,
      "Total": 300
    },
    {
      "Number": 224,
      "Name": "Octillery",
      "Type 1": "Water",
      "Type 2": "",
      "HP": 75,
      "Attack": 105,
      "Defense": 75,
      "Sp. Atk": 105,
      "Sp. Def": 75,
      "Speed": 45,
      "Total": 480
    },
    {
      "Number": 225,
      "Name": "Delibird",
      "Type 1": "Ice",
      "Type 2": "Flying",
      "HP": 45,
      "Attack": 55,
      "Defense": 45,
      "Sp. Atk": 65,
      "Sp. Def": 45,
      "Speed": 75,
      "Total": 330
    },
    {
      "Number": 226,
      "Name": "Mantine",
      "Type 1": "Water",
      "Type 2": "Flying",
      "HP": 65,
      "Attack": 40,
      "Defense": 70,
      "Sp. Atk": 80,
      "Sp. Def": 140,
      "Speed": 70,
      "Total": 465
    },
    {
      "Number": 227,
      "Name": "Skarmory",
      "Type 1": "Steel",
      "Type 2": "Flying",
      "HP": 65,
      "Attack": 80,
      "Defense": 140,
      "Sp. Atk": 40,
      "Sp. Def": 70,
      "Speed": 70,
      "Total": 465
    },
    {
      "Number": 228,
      "Name": "Houndour",
      "Type 1": "Dark",
      "Type 2": "Fire",
      "HP": 45,
      "Attack": 60,
      "Defense": 30,
      "Sp. Atk": 80,
      "Sp. Def": 50,
      "Speed": 65,
      "Total": 330
    },
    {
      "Number": 229,
      "Name": "Houndoom",
      "Type 1": "Dark",
      "Type 2": "Fire",
      "HP": 75,
      "Attack": 90,
      "Defense": 50,
      "Sp. Atk": 110,
      "Sp. Def": 80,
      "Speed": 95,
      "Total": 500
    },
    {
      "Number": 230,
      "Name": "Kingdra",
      "Type 1": "Water",
      "Type 2": "Dragon",
      "HP": 75,
      "Attack": 95,
      "Defense": 95,
      "Sp. Atk": 95,
      "Sp. Def": 95,
      "Speed": 85,
      "Total": 540
    },
    {
      "Number": 231,
      "Name": "Phanpy",
      "Type 1": "Ground",
      "Type 2": "",
      "HP": 90,
      "Attack": 60,
      "Defense": 60,
      "Sp. Atk": 40,
      "Sp. Def": 40,
      "Speed": 40,
      "Total": 330
    },
    {
      "Number": 232,
      "Name": "Donphan",
      "Type 1": "Ground",
      "Type 2": "",
      "HP": 90,
      "Attack": 120,
      "Defense": 120,
      "Sp. Atk": 60,
      "Sp. Def": 60,
      "Speed": 50,
      "Total": 500
    },
    {
      "Number": 233,
      "Name": "Porygon2",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 85,
      "Attack": 80,
      "Defense": 90,
      "Sp. Atk": 105,
      "Sp. Def": 95,
      "Speed": 60,
      "Total": 515
    },
    {
      "Number": 234,
      "Name": "Stantler",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 73,
      "Attack": 95,
      "Defense": 62,
      "Sp. Atk": 85,
      "Sp. Def": 65,
      "Speed": 85,
      "Total": 465
    },
    {
      "Number": 235,
      "Name": "Smeargle",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 55,
      "Attack": 20,
      "Defense": 35,
      "Sp. Atk": 20,
      "Sp. Def": 45,
      "Speed": 75,
      "Total": 250
    },
    {
      "Number": 236,
      "Name": "Tyrogue",
      "Type 1": "Fighting",
      "Type 2": "",
      "HP": 35,
      "Attack": 35,
      "Defense": 35,
      "Sp. Atk": 35,
      "Sp. Def": 35,
      "Speed": 35,
      "Total": 210
    },
    {
      "Number": 237,
      "Name": "Hitmontop",
      "Type 1": "Fighting",
      "Type 2": "",
      "HP": 50,
      "Attack": 95,
      "Defense": 95,
      "Sp. Atk": 35,
      "Sp. Def": 110,
      "Speed": 70,
      "Total": 455
    },
    {
      "Number": 238,
      "Name": "Smoochum",
      "Type 1": "Ice",
      "Type 2": "Psychic",
      "HP": 45,
      "Attack": 30,
      "Defense": 15,
      "Sp. Atk": 85,
      "Sp. Def": 65,
      "Speed": 65,
      "Total": 305
    },
    {
      "Number": 239,
      "Name": "Elekid",
      "Type 1": "Electric",
      "Type 2": "",
      "HP": 45,
      "Attack": 63,
      "Defense": 37,
      "Sp. Atk": 65,
      "Sp. Def": 55,
      "Speed": 95,
      "Total": 360
    },
    {
      "Number": 240,
      "Name": "Magby",
      "Type 1": "Fire",
      "Type 2": "",
      "HP": 45,
      "Attack": 75,
      "Defense": 37,
      "Sp. Atk": 70,
      "Sp. Def": 55,
      "Speed": 83,
      "Total": 365
    },
    {
      "Number": 241,
      "Name": "Miltank",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 95,
      "Attack": 80,
      "Defense": 105,
      "Sp. Atk": 40,
      "Sp. Def": 70,
      "Speed": 100,
      "Total": 490
    },
    {
      "Number": 242,
      "Name": "Blissey",
      "Type 1": "Normal",
      "Type 2": "",
      "HP": 255,
      "Attack": 10,
      "Defense": 10,
      "Sp. Atk": 75,
      "Sp. Def": 135,
      "Speed": 55,
      "Total": 540
    },
    {
      "Number": 243,
      "Name": "Raikou",
      "Type 1": "Electric",
      "Type 2": "",
      "HP": 90,
      "Attack": 85,
      "Defense": 75,
      "Sp. Atk": 115,
      "Sp. Def": 100,
      "Speed": 115,
      "Total": 580
    },
    {
      "Number": 244,
      "Name": "Entei",
      "Type 1": "Fire",
      "Type 2": "",
      "HP": 115,
      "Attack": 115,
      "Defense": 85,
      "Sp. Atk": 90,
      "Sp. Def": 75,
      "Speed": 100,
      "Total": 580
    },
    {
      "Number": 245,
      "Name": "Suicune",
      "Type 1": "Water",
      "Type 2": "",
      "HP": 100,
      "Attack": 75,
      "Defense": 115,
      "Sp. Atk": 90,
      "Sp. Def": 115,
      "Speed": 85,
      "Total": 580
    },
    {
      "Number": 246,
      "Name": "Larvitar",
      "Type 1": "Rock",
      "Type 2": "Ground",
      "HP": 50,
      "Attack": 64,
      "Defense": 50,
      "Sp. Atk": 45,
      "Sp. Def": 50,
      "Speed": 41,
      "Total": 300
    },
    {
      "Number": 247,
      "Name": "Pupitar",
      "Type 1": "Rock",
      "Type 2": "Ground",
      "HP": 70,
      "Attack": 84,
      "Defense": 70,
      "Sp. Atk": 65,
      "Sp. Def": 70,
      "Speed": 51,
      "Total": 410
    },
    {
      "Number": 248,
      "Name": "Tyranitar",
      "Type 1": "Rock",
      "Type 2": "Dark",
      "HP": 100,
      "Attack": 134,
      "Defense": 110,
      "Sp. Atk": 95,
      "Sp. Def": 100,
      "Speed": 61,
      "Total": 600
    },
    {
      "Number": 249,
      "Name": "Lugia",
      "Type 1": "Psychic",
      "Type 2": "Flying",
      "HP": 106,
      "Attack": 90,
      "Defense": 130,
      "Sp. Atk": 90,
      "Sp. Def": 154,
      "Speed": 110,
      "Total": 680
    },
    {
      "Number": 250,
      "Name": "Ho-Oh",
      "Type 1": "Fire",
      "Type 2": "Flying",
      "HP": 106,
      "Attack": 130,
      "Defense": 90,
      "Sp. Atk": 110,
      "Sp. Def": 154,
      "Speed": 90,
      "Total": 680
    },
    {
      "Number": 251,
      "Name": "Celebi",
      "Type 1": "Psychic",
      "Type 2": "Grass",
      "HP": 100,
      "Attack": 100,
      "Defense": 100,
      "Sp. Atk": 100,
      "Sp. Def": 100,
      "Speed": 100,
      "Total": 600
    }
   ];
var Pokemon = nodecg.Replicant('Pokemon');
var single = nodecg.Replicant('singleRun');

var localData;
var defaultdata = {
    TrainerE:{
        "Number": 0,
        "Name": "",
        "Type 1": "",
        "Type 2": "",
        "Total": 0,
        "HP": 0,
        "Attack": 0,
        "Defense": 0,
        "Sp. Atk": 0,
        "Sp. Def": 0,
        "Speed": 0,
        "Generation": 0,
        "Legendary": false
      },
    TrainerD:{
        "Number": 0,
        "Name": "",
        "Type 1": "",
        "Type 2": "",
        "Total": 0,
        "HP": 0,
        "Attack": 0,
        "Defense": 0,
        "Sp. Atk": 0,
        "Sp. Def": 0,
        "Speed": 0,
        "Generation": 0,
        "Legendary": false
      }
};

Pokemon.on('change', (newVal, oldVal) => {
    if(newVal && newVal != oldVal){
        localData = newVal;
        nodecg.readReplicant("singleRun",'rbr', (pkData) => {
            if(pkData.layout == "fir"){
                setup(newVal);
            }
        });
    }
    if(!newVal){
        newVal = defaultdata;
    }
});

single.on('change', (newVal, oldVal) => {    
    if(newVal.layout == "fir"){
        nodecg.readReplicant("Pokemon",'rbr', (pkData) => {
            setup(pkData)
        });
    }else{
        console.log("what")
        document.getElementById("dashBoardPokemon").className = "hidden";
        Pokemon.value = defaultdata;
    }
});

function createSelect(gen,select,selected){
    var html = "<option value>Pokemon</option>";
    //var filtered = database.filter(e=>e["Generation"] <= gen && (!e["Name"].includes("Mega") || e["Name"].indexOf("Mega")==0));
    filtered = database;
    if(filtered){
      filtered.forEach(pk=>{
          html += `<option value="${pk["Number"]}" ${selected == pk["Number"]?"selected":""}>${pk["Name"]}</option>`
      })
    }
    select.innerHTML = html;
}

function setup(newVal){
    document.getElementById("dashBoardPokemon").className = "";
    var selectE = document.getElementById("dashBoardPokemonE");
    var selectD = document.getElementById("dashBoardPokemonD");
    if(newVal.TrainerE){
      createSelect(2,selectE,newVal.TrainerE?newVal.TrainerE["Number"]:0);
    }
    if(newVal.TrainerD){
      createSelect(2,selectD,newVal.TrainerD?newVal.TrainerD["Number"]:0);
    }
}

function searchPkmn(Num){
    return database.find(e=>e["Number"] == Num);
}

function changePkmn(input,side){
    localData["Trainer"+side] = searchPkmn(input.value)
}